apiVersion: v1
kind: Secret
metadata:
  name: grafana-secret
  namespace: monitoring # change to your namespace if different
type: Opaque
data:
  smtp_username: "base64_username"
  smtp_password: "base64_password"
