grafana:
  smtp:
    enabled: true
    existingSecret: "grafana-smtp-secret"
    passwordKey: "smtp_password"
    userKey: "smtp_username"

  grafana.ini:
    smtp:
      enabled: true
      existingSecret: "grafana-smtp-secret"
      passwordKey: "smtp_password"
      userKey: "smtp_username"
      host: sandbox.smtp.mailtrap.io:587
      from_address: alerts@example.com





