# https://github.com/grafana/helm-charts/blob/main/charts/grafana/values.yaml
grafana:
  # admin credentials
  adminUser: "admin"
  adminPassword: "admin@123"
  
  smtp:
    enabled: false
    existingSecret: "grafana-secret"
    passwordKey: "smtp_password"
    userKey: "smtp_username"

  grafana.ini:
    # smtp setup
    smtp:
      enabled: false
      # set your own SMTP hostname
      host: sandbox.smtp.mailtrap.io:587
      from_address: alerts@example.com





